# Generated by Django 5.0.7 on 2024-07-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retreat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retreat',
            name='condition',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='retreat',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='retreat',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='retreat',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
